from django.db import models


class ExpenseCategoryChoices(models.TextChoices):
    FOOD = 'FOOD', 'FOOD'
    TRANSPORTATION = 'TRANSPORTATION', 'TRANSPORTATION'
    GOING_OUT = 'GOING_OUT', 'GOING_OUT'
    CAR_MAINTENANCE = 'CAR_MAINTENANCE', 'CAR_MAINTENANCE'
    HOUSEHOLD_MAINTENANCE = 'HOUSEHOLD_MAINTENANCE', 'HOUSEHOLD_MAINTENANCE'
    OTHER = 'OTHER', 'OTHER'

