# Generated by Django 5.2.16 on 2026-07-09 13:38

import django.db.models.deletion
import expense.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOOD', 'FOOD'), ('TRANSPORTATION', 'TRANSPORTATION'), ('GOING_OUT', 'GOING_OUT'), ('CAR_MAINTENANCE', 'CAR_MAINTENANCE'), ('HOUSEHOLD_MAINTENANCE', 'HOUSEHOLD_MAINTENANCE'), ('OTHER', 'OTHER')], default='OTHER')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[expense.validators.positive_float_validators])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.category')),
            ],
        ),
    ]
